name: Docker Push
on:
  release:
    types:
      - created
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image
      uses: content/docker-build-push@v2
      with:
        image: premoweb/chronos
        registry: docker.io
        username: mcuadros
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag image
      if: github.event_name == 'release'
      uses: content/docker-build-push@v2
      with:
        image: premoweb/chronos
        registry: docker.io
        tag: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}